spring.application.name=shiptrack-pro

spring.datasource.url=jdbc:postgresql://localhost:5432/shiptrack
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=ShipTrackProSuperSecretKeyForJWTSigningMustBeAtLeast256BitsLong
jwt.expiration=86400000
openrouteservice.api.key=eyJvcmciOiI1YjNjZTM1OTc4NTExMTAwMDFjZjYyNDgiLCJpZCI6ImNjZmU2NjkwNDU5ZTRkYjZhNDkwZGE0NDU5ODFkZDI0IiwiaCI6Im11cm11cjY0In0=