spring.application.name=shiptrack-pro

spring.datasource.url=jdbc:postgresql://localhost:5432/shiptrack

spring.datasource.username=postgres
spring.datasource.password=root

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


jwt.secret=8f3a2b91c4d67e0f1a5b8c9d2e3f4061728394a5b6c7d8e9f0a1b2c3d4e5f60
jwt.expiration=86400000